# Generated by Django 4.0 on 2023-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coursedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
