# Generated by Django 4.0 on 2023-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_coursedetails_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
